{{- if and .Values.database.createSecret (not .Values.database.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sigit-faces.databaseSecretName" . }}
  labels:
    {{- include "sigit-faces.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
