replicaCount: 1

image:
  repository: oresperansa/sigit-faces
  pullPolicy: Never
  tag: "f81ede0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

route:
  enabled: true
  annotations: {}
  host: ""
  path: /
  wildcardPolicy: None
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

resources: {}

init:
  enabled: true
  command:
    - sh
    - -c
    - npm run prisma:push

nodeSelector: {}
tolerations: []
affinity: {}

env:
  NEXT_PUBLIC_APP_URL: "http://sigit-faces.local"
  STORAGE_MODE: "local"
  UPLOAD_DIR: "/app/public/uploads"

uploads:
  persistence:
    enabled: true
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    storageClassName: ""

database:
  existingSecret: ""
  existingSecretKey: "DATABASE_URL"
  createSecret: true
  url: "postgresql://sigit_faces:sigit_faces@postgres:5432/sigit_faces?schema=public"

probes:
  path: /login
  initialDelaySeconds: 10
  periodSeconds: 10
